version: '3'

services:
  spm-client:
   image: sematext/spm-client:auto-discovery
   volumes: 
      # spm-client > v1.31.65 requires access to docker socket
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
   image: redis:latest
   environment: 
     SPM_TOKEN: ${SPM_TOKEN}


