version: "3"
services:
  master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master 
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: localhost
      SPARK_MASTER_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.rmi.port=3001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=master
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
      - 3000
      - 8080
      - 18080
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/metrics.properties:/usr/spark-2.2.1/conf/metrics.properties:ro
      - ./data:/tmp/data

  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.rmi.port=3001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=worker
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
      - 3000
    ports:
      - 8081:8081
    volumes:
      - ./conf/metrics.properties:/usr/spark-2.2.1/conf/metrics.properties:ro
      - ./data:/tmp/data

  spm-client:
   image: sematext/spm-client
   container_name: spm-client
   links:
     - worker
     - master
   environment:
     - SPM_CONFIG=${SPM_TOKEN} spark standalone spark-worker -P:SPARK_API_HOST=worker -P:SPARK_API_PORT=4040 -P:SPM_MONITOR_JMX_PARAMS=-Dspm.remote.jmx.url=worker:3000
   volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
