apiVersion: v1
kind: Pod
metadata:
  name: some-mongo
spec:
  containers:
    - image: launcher.gcr.io/google/mongodb3
      name: mongo
      ports:
        - containerPort: 27017
      env:
        - name: SPM_TOKEN
          value: ${SPM_TOKEN}



