version: '3'

services:
  spm-client:
   image: sematext/spm-client:auto-discovery
   privileged: true
   volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    
  mysql2:
    image: mysql
    ports:
      - 6603:3306
    environment:
      SPM_TOKEN: 3c3e0027-c91b-468d-ab59-ebf057c8603e
      MYSQL_USER: spm
      MYSQL_PASSWORD: spm-user-password
      MYSQL_ROOT_PASSWORD: mysqlRootPassword
    volumes:
      - /tmp/mysql:/var/lib/mysql

