version: '2'

services:
  spm-client:
   image: sematext/spm-client:auto-discovery
   hostname: spm-client-nginx
   privileged: true
   volumes: 
    # spm-client > v1.31.65 requires access to docker socket
    - /var/run/docker.sock:/var/run/docker.sock
   #environment:
    # token nginx nginx_status_url
    # - SPM_CONFIG=${SPM_TOKEN} nginx http://nginx:80/nginx_status
   links: 
    - nginx

  nginx:
   image: nginx:latest
   ports:
    - "9001:80"
   environment: 
    - SPM_TOKEN=0d1de046-1608-4893-808e-4fdd28d087f6
   volumes: 
    - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf
    # default.conf contains following entry to activate the status url:
    # location /nginx_status {
    #   # Turn on nginx stats
    #   stub_status on;
    #   # I do not need logs for stats
    #   access_log   off;
    #   # Security: Please use you local IP address instead ...
    #   allow all;
    # }
    