version: '3'

services:
  spm-client:
   image: sematext/spm-client:auto-discovery
   privileged: true
   volumes: 
    - /var/run/docker.sock:/var/run/docker.sock

  nginx:
   image: nginx:latest
   ports:
    - "9001:80"
   environment: 
    - SPM_TOKEN=${SPM_TOKEN}
   volumes: 
    - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf
    # default.conf contains following entry to activate the status url:
    # location /nginx_status {
    #   # Turn on nginx stats
    #   stub_status on;
    #   # I do not need logs for stats
    #   access_log   off;
    #   # Security: Please use you local IP address instead ...
    #   allow all;
    # }
    