services:
  spm-client:
   image: sematext/spm-client:auto-discovery
   volumes: 
     - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    labels: 
      - SPM_TOKEN=${SPM_TOKEN}
    environment:
      JMXPORT: 3000

